#
# Autogenerated by Thrift Compiler (0.9.0-dev)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

module EmptyService
  class Client
    include ::Thrift::Client

  end

  # HELPER FUNCTIONS AND STRUCTURES

  # SERVICE MOCK

  class Mock
  end
end

